name: Push 
on:  push 

jobs:
  build:
    #if: startsWith(github.event.head_commit.message, 'Finally Merge')
    runs-on: ubuntu-latest
    steps:
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2


    - name: Create local changes
      run: |
        cat > sales661.txt
    - name: Commit files
      run: |
        
        git add --all
        git commit -m "Add changes" -a
        git tag v5.1
        git push origin v5.1

     
    #- name: Push changes
    #  uses: Woile/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GPR_ACCESS_TOKEN }}
    #   tags: "true"
