name: create zip 
on: 
  push: 
    
jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - run:  mkdir frontend-zip
    #- run: zip -qq -r ./frontend-zip/frontend.zip ./projects/frontend/
    - uses: montudor/action-zip@v0.1.0
      with:
         args: zip -qq -r ./frontend-zip/frontend.zip ./projects/frontend/
    - name: Upload zip package to release
      uses: svenstaro/upload-release-action@v1-release
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./frontend-zip/frontend.zip
          asset_name: frontend2
          tag: ${{ github.ref }}
